[package]
name = "password-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.8"
web-sys = "0.3.60"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }